# This workflow will do a clean installation of node dependencies, cache/restore them, build the source code and run tests across different versions of node
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-nodejs

name: Node.js CI

on:
  pull_request:
    branches: [ "main" ]
  workflow_dispatch:

jobs:
  test:
    runs-on: ubuntu-latest

    defaults:
      run:
        working-directory: testing-with-workout-project-github-classroom

    strategy:
      matrix:
        node-version: [20, 22, 24]
        # See supported Node.js release schedule at https://nodejs.org/en/about/releases/

    steps:
    - uses: actions/checkout@v4
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v4
      with:
        node-version: ${{ matrix.node-version }}
        cache: 'npm'
    - run: npm ci
    - run: npm test
    - name: Test using Action secret
      env:
        MY_SECRET: ${{ secrets.MY_SECRET }}
      run: |
        echo "The secret value is $MY_SECRET"
    - name: Fetch repo info using GITHUB_TOKEN
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      run: |
        curl -s -H "Authorization: Bearer $GITHUB_TOKEN" \
          https://api.github.com/repos/${{ github.repository }}
